# Generated by Django 4.2 on 2024-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('BEST', 'BEST')], max_length=4),
        ),
    ]
