# Generated by Django 4.2 on 2024-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_alter_produkitem_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'New'), ('SALE', 'Sale'), ('BEST', 'Best')], max_length=4),
        ),
    ]
