# Generated by Django 4.2 on 2024-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_alter_produkitem_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'Baru'), ('SALE', 'Disc'), ('BEST', 'Jempol')], max_length=4),
        ),
    ]
